language: common-lisp
sudo: required

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros -s prove -e '(progn (ql:quickload (list :the-prisoners :the-prisoners-test)) (or (prove:run :the-prisoners-test) (uiop:quit -1)))'